application: sandbox4sinmetal-tg
module: createjs-study
version: 201408021435
runtime: go
api_version: go1

basic_scaling:
  max_instances: 1

handlers:
- url: /script
  static_dir: script

- url: /index.html
  static_files: index.html
  upload: index.html

- url: /.*
  script: _go_app